import { EnvelopeSimple, MapPin, Phone, WhatsappLogo } from "@phosphor-icons/react/dist/ssr";
import Image from "next/image";
import Link from "next/link";
import { faqs, whatsappNumber } from "@/data/site-data";

export const metadata = { title: "Kontak & FAQ | Maulana Transport Jogja", description: "Hubungi Maulana Transport dan lihat pertanyaan umum seputar rental mobil di Yogyakarta." };

export default function ContactPage() {
  return <><section className="page-hero"><div className="container"><div className="eyebrow">Kontak & bantuan</div><h1 className="display">Satu pesan untuk mulai jalan.</h1><p>Hubungi admin untuk mengecek ketersediaan armada, detail rute, atau kebutuhan perjalanan khusus.</p></div></section><section className="section"><div className="container contact-grid"><div><div className="eyebrow">Temukan kami</div><h2 className="title contact-title">Maulana Transport Jogja.</h2><div className="contact-list"><div className="contact-item"><MapPin size={22} className="contact-icon" /><div><strong>Area layanan</strong><span>Yogyakarta dan rute luar kota di sekitarnya</span></div></div><div className="contact-item"><Phone size={22} className="contact-icon" /><div><strong>Telepon</strong><a href="tel:+6281234567890">+62 812 3456 7890</a></div></div><div className="contact-item"><EnvelopeSimple size={22} className="contact-icon" /><div><strong>Email</strong><a href="mailto:halo@maulanatransport.com">halo@maulanatransport.com</a></div></div></div><Link className="button button-primary contact-action" href={`https://wa.me/${whatsappNumber}`} target="_blank" rel="noreferrer"><WhatsappLogo size={18} weight="fill" /> Chat WhatsApp</Link></div><div className="map-frame"><Image className="map-image" src="https://images.unsplash.com/photo-1524666041070-9f8763d7be4e?auto=format&fit=crop&w=1400&q=80" alt="Jalan kota di Yogyakarta" fill sizes="(max-width: 1000px) 100vw, 55vw" /><div className="map-overlay" /><div className="map-frame-content"><MapPin size={32} weight="fill" /><h2>Rute berawal dari Jogja</h2><p>Kirim detail perjalanan Anda. Admin akan membantu mencocokkan kendaraan dan rute yang sesuai.</p><Link className="button button-ghost map-cta" href="/pesan">Kirim kebutuhan Anda</Link></div></div></div></section><section className="section line-top"><div className="container faq-wrap"><div className="eyebrow">Pertanyaan umum</div><h2>Yang perlu Anda tahu.</h2>{faqs.map((faq) => <details className="faq-item" key={faq.question}><summary>{faq.question}<span>+</span></summary><p>{faq.answer}</p></details>)}</div></section></>;
}
